### ISSUE TITLE
Crashed sur

### ISSUE THREAD

**Issue by Mrvishal2k2** [MaxxRider2/Max-Torrent-Leech-V2#2]
😂 where is start.sh file 
It totally crashed

**Comment by MaxxRider2** [comment]
Mei nehi manta 
Video dikhao 😂😂😂

**Comment by MaxxRider2** [comment]
🤓🤓🤓

**Comment by myselfloaders** [comment]
> Mei nehi manta Video dikhao 😂😂😂

Lmao
